# Generated by Django 2.1.5 on 2019-01-26 16:49

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department', models.CharField(choices=[(1, '應用英語'), (2, '應用日語'), (3, '應用中文'), (4, '資訊工程'), (5, '資訊管理'), (6, '護理')], default=1, max_length=10, verbose_name='科系')),
                ('grade', models.CharField(choices=[(1, '一年級'), (2, '二年級'), (3, '三年級'), (4, '四年級'), (5, '五年級')], default=1, max_length=10, verbose_name='年級')),
                ('student_ID', models.CharField(max_length=11, verbose_name='學號')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10, verbose_name='性別')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手機號碼')),
                ('email', models.EmailField(max_length=50, verbose_name='信箱')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶訊息',
                'verbose_name_plural': '用戶訊息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('image', models.ImageField(upload_to='banner/%Y%m', verbose_name='輪播圖')),
                ('url', models.URLField(verbose_name='訪問地址')),
                ('index', models.IntegerField(default=100, verbose_name='順序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間')),
            ],
            options={
                'verbose_name': '輪播圖',
                'verbose_name_plural': '輪播圖',
            },
        ),
    ]
