# Generated by Django 2.1.5 on 2019-02-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='female', max_length=10, verbose_name='性別'),
        ),
    ]
