# Generated by Django 2.1.5 on 2019-02-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190203_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
