# Generated by Django 3.0.6 on 2020-06-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200604_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
