# Generated by Django 3.0.6 on 2020-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/img/hs.jpg', null=True, upload_to='upload'),
        ),
    ]
