# Generated by Django 3.0.6 on 2020-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200604_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/img/hs.jpg', null=True, upload_to='upload/%Y/%m/%d/%H/%M/%S/%f/'),
        ),
    ]
