# Generated by Django 3.0.6 on 2020-06-11 07:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200611_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/img/hs.jpg', null=True, upload_to=users.models.PathAndRename('user_img')),
        ),
    ]
