# Generated by Django 2.1.5 on 2019-02-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190206_0819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerCourse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
    ]
