# Generated by Django 2.1.5 on 2019-02-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190213_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100, verbose_name='單字')),
                ('kk', models.CharField(max_length=100, verbose_name='kk音標')),
                ('subject', models.CharField(max_length=100, verbose_name='詞性')),
                ('description', models.CharField(max_length=100, verbose_name='解釋')),
                ('example', models.CharField(max_length=100, verbose_name='例句')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lesson', verbose_name='章節名稱')),
            ],
            options={
                'verbose_name': '單字',
                'verbose_name_plural': '單字',
            },
        ),
    ]
