# Generated by Django 2.1.5 on 2019-02-16 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190213_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='封面圖'),
        ),
        migrations.AlterField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='words',
            name='chinese',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='中文'),
        ),
        migrations.AlterField(
            model_name='words',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='解釋'),
        ),
        migrations.AlterField(
            model_name='words',
            name='example',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='例句'),
        ),
        migrations.AlterField(
            model_name='words',
            name='kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='kk音標'),
        ),
        migrations.AlterField(
            model_name='words',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='詞性'),
        ),
    ]
