# Generated by Django 2.1.5 on 2019-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190216_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='example_tw',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='例句中文'),
        ),
    ]
