# Generated by Django 2.1.5 on 2019-03-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_words_example_tw'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='example_json',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='例句替換資料庫'),
        ),
    ]
