# Generated by Django 2.0 on 2019-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_words_example_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='example_svg',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='例句詞性結構樹'),
        ),
    ]
