# Generated by Django 2.0 on 2019-04-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_words_example_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='example_svg',
            field=models.CharField(blank=True, max_length=90000, null=True, verbose_name='例句詞性結構樹'),
        ),
    ]
