# Generated by Django 2.0 on 2020-01-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20200109_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examples',
            name='words',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='單字'),
        ),
    ]
