# Generated by Django 3.0.6 on 2020-06-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_auto_20200603_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='likes',
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='課程簡介'),
        ),
        migrations.AlterField(
            model_name='examples',
            name='words',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Words', verbose_name='單字名稱'),
        ),
    ]
