"""
Django settings for elearning project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^^a_ul!&&6huiv1*hx*-kul_8o5!&s)b*!k2zl#o^$$q7qdy5d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.12', 'localhost', '127.0.0.1' ,'0.0.0.0','192.168.43.198','192.168.1.201']

AUTH_USER_MODEL = 'users.UserProfile'
# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'reversion',
    
    'users',
    'course',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elearning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elearning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)

STATIC_ROOT=os.path.join(BASE_DIR,"/static/")

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,'templates'),
)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# AUTHENTICATION_BACKENDS = (
#     'users.views.CustomBackend',
# )

AUTHENTICATION_BACKENDS = (
    'users.views.Student_IDBackend',
)





MEDIA_URL = '/upload/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload').replace("\\", "/")

SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = False
# SIMPLEUI_HOME_TITLE = 'GOOGLE' 
# SIMPLEUI_HOME_PAGE = 'https://www.google.com' 
SIMPLEUI_HOME_ICON = 'el el-icon-platform-eleme'
SIMPLEUI_HOME_TITLE ="NUTC ELEARNING"

SIMPLEUI_LOGO = 'https://upload.wikimedia.org/wikipedia/zh/thumb/7/77/NUTC_logo.gif/220px-NUTC_logo.gif'

import time
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['NUTC Elearning', '課程管理', '學生管理','認證與授權'],     
    'dynamic': False,    
    'menus': [
    {
        'app': 'course',
        'name': '課程管理',
        'icon': 'fa fa-book',
        'models': [{
            'name': 'WORD',
            'url': 'course/words/',
            'icon': 'fa fa-font'
        }, {
            'name': 'LESSON',
            'url': 'course/lesson/',
            'icon': 'far fa-file-alt'
        },{
            'name': 'COURSE',
            'url': 'course/course/',
            'icon': 'fas fa-book-open'
        }]
    },{
        'app': 'users',
        'name': '學生管理',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '學生名單',
            'icon': 'fa fa-user',
            'url': 'users/userprofile/'
        }]
    },{
        'app': 'auth',
        'name': '認證與授權',
        'icon': 'fas fa-shield-alt',
        'models': [{
            'name': '群組',
            'icon': 'fas fa-users-cog',
            'url': 'auth/group/'
        }]
    }]
}
